gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to CHALLENGE ISLAND!\p"
	.string "This hack is associated with.\p"
	.string "TEAM AQUA HIDEOUT and \n"
	.string "OUR GLORIOUS LEADER ARCHIE.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "KYOGRE PRAISE BE.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "You will play the game as A\n"
	.string "POKEMON RESEARCHER.\p"
	.string "who unfortunatly gets stranded on\n"
	.string "an Island.\l"
	.string "You will need overworld.\p"
	.string "navigation skills\n"
	.string "Battle prowess\p"
	.string "And lots of pokemon trivia!\n"
	.string "Remember to practice\p"
	.string "Good pokemon game ettiquette\n"
	.string "And save often!.\p"
	.string "Some puzzles are designed \n"
	.string "To softlock you\l"
	.string "Keep that in mind.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who I hired\n"
	.string "To do research.\l"
	.string "(I hope thats not child labor)\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Every puzzle is solvable\n"
	.string "Remember to analyze,\l"
	.string "and approach every problem\p"
	.string "from different angles.\n"
	.string "Good Luck Researcher!\p"
	.string "$"
